export const projectId = "jvgejuvblydfyfpghwsz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2Z2VqdXZibHlkZnlmcGdod3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMzA5MzgsImV4cCI6MjA5MzYwNjkzOH0.SLqqmtvf_yak9jQIb8NgdIpkPKiaJ3B09CEuCJFH_L0"
export const API_URL = `https://${projectId}.supabase.co/functions/v1/admin_api`;